PortfolioMaker/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :projects
end

PortfolioMaker/app/models/project.rb
class Project < ActiveRecord::Base
  validates	:title, presence: true
  validates	:description, presence: true

# wait till we add user
# belongs_to :user

end

PortfolioMaker/app/models/user.rb
class User < ActiveRecord::Base
	authenticates_with_sorcery!

	validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
	validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
	validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

	validates :email, uniqueness: true
	validates :name, presence: true
end

PortfolioMaker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

PortfolioMaker/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :brief, :description, :github_repo, :demo_site_url, :languages_used, :other_features, :project_image_url)
    end
end

PortfolioMaker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :phone, :github_profile, :bio, :profile_image, :password, :password_confirmation)
    end
end

PortfolioMaker/app/helpers/application_helper.rb
module ApplicationHelper
end

PortfolioMaker/app/helpers/projects_helper.rb
module ProjectsHelper
end

PortfolioMaker/app/helpers/users_helper.rb
module UsersHelper
end

PortfolioMaker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<script src="https://use.fontawesome.com/4e2899de1b.js"></script>
  <title>PortfolioMaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


	<div class="container">
		<%= yield %>
	</div>


</body>
</html>

PortfolioMaker/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :brief %><br>
    <%= f.text_field :brief %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :github_repo %><br>
    <%= f.text_field :github_repo %>
  </div>
  <div class="field">
    <%= f.label :demo_site_url %><br>
    <%= f.text_field :demo_site_url %>
  </div>
  <div class="field">
    <%= f.label :languages_used %><br>
    <%= f.text_area :languages_used %>
  </div>
  <div class="field">
    <%= f.label :other_features %><br>
    <%= f.text_area :other_features %>
  </div>
  <div class="field">
    <%= f.label :project_image_url %><br>
    <%= f.text_field :project_image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PortfolioMaker/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

PortfolioMaker/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<div class="container">
<div class="row">
  <div class="card-deck-wrapper">
    <div class="card-deck">
      <% @projects.each do |project| %>
        <div class="card">
          <img class="card-img-top img-fluid" src="<%= project.project_image_url %>" data-src="..." alt="Screenshot Image of <%= project.title %> Site">
          <div class="card-block">
            <h4 class="card-title"><%= project.title %></h4>
            <p class="card-text"><%= project.brief %></p>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><%= project.languages_used %></li>
              <li class="list-group-item"><%= project.other_features %></li>
            </ul>
            <div class="card-block">
              <a href="<%= project.github_repo %>" class="card-link">View Code</a>
              <a href="<%= project.demo_site_url %>" class="card-link">View Demo</a>
              <br>
              <%= link_to 'Show', project %>
              <%= link_to 'Edit', edit_project_path(project) %>
              <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>
<%= link_to 'New Project', new_project_path %>

PortfolioMaker/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

PortfolioMaker/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Brief:</strong>
  <%= @project.brief %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Github repo:</strong>
  <%= @project.github_repo %>
</p>

<p>
  <strong>Demo site url:</strong>
  <%= @project.demo_site_url %>
</p>

<p>
  <strong>Languages used:</strong>
  <%= @project.languages_used %>
</p>

<p>
  <strong>Other features:</strong>
  <%= @project.other_features %>
</p>

<p>
  <strong>Project image url:</strong>
  <%= @project.project_image_url %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

PortfolioMaker/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :github_profile %><br>
    <%= f.text_field :github_profile %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :profile_image %><br>
    <%= f.text_field :profile_image %>
  </div>
  <div>
     <%= f.label :password %><br />
     <%= f.password_field :password %>
  </div>
  <div>
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PortfolioMaker/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

PortfolioMaker/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Github profile</th>
      <th>Bio</th>
      <th>Profile image</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.phone %></td>
        <td><%= user.github_profile %></td>
        <td><%= user.bio %></td>
        <td><img src="<%= user.profile_image %>" class="profile-image"></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

PortfolioMaker/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

PortfolioMaker/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Github profile:</strong>
  <%= @user.github_profile %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Profile image:</strong>
  <img src="<%= @user.profile_image %>" class="profile-image">
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>